### ISSUE TITLE
Dead Letter Queue input should support 'add_fields' and 'tags' plugin options

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-input-dead_letter_queue#11]
The Dead Letter Queue input plugin does not currently call the decorate method on the event, meaning that any fields and tags added in the plugin configuration, (as documented  [here](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-dead_letter_queue.html#plugins-inputs-dead_letter_queue-common-options)), are not set on the event.

**Comment by dedemorton** [comment]
@robbavey Should we remove these options from the doc until they are supported?

**Comment by robbavey** [comment]
@dedemorton Good question - @suyograo?

**Comment by robbavey** [comment]
@dedemorton, @suyograo If we agree that this is a bug, and that the dlq plugin should support it, then the change is trivial -- #12 -- if not, docs should be changed
