### ISSUE TITLE
DLQ plugin_id contains plugin_type while plugin_type contains plugin_id

### ISSUE THREAD

**Issue by cstegm** [logstash-plugins/logstash-input-dead_letter_queue#48]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`): 8.6.1   
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker): RPM
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): systemd
4. How was the Logstash Plugin installed: shipped with rpm logstash elastic.co repo default

**JVM** (e.g. `java -version`): that what is shipped with logstash rpm
**OS version** (`uname -a` if on a Unix-like system): Centos 7
**Description of the problem including expected versus actual behavior**:
```
filter {
    mutate {
        add_field => {
            "error_reason" => "%{[@metadata][dead_letter_queue][reason]}"
            "plugin_id" => "%{[@metadata][dead_letter_queue][plugin_id]}"
            "plugin_type" => "%{[@metadata][dead_letter_queue][plugin_type]}"
            "entry_time" => "%{[@metadata][dead_letter_queue][entry_time]}"
        }
    }
}
```

Looking into the event plugin_id contains the type and plugin_type the id, while it should be the other way around

**Steps to reproduce**:

Setup a DLQ pipline and use the filter above.

**Comment by gemaliano** [comment]
Steps to reproduce (8.6.1):
Following [processing data with mapping errors doc](https://www.elastic.co/guide/en/logstash/8.6/dead-letter-queues.html#dlq-example):
Create mapping on elasticsearch:
```json
PUT /test-000001
{
  "mappings": {
    "properties": {
      "geoip": {
        "properties": {
          "location": { "type": "geo_point" }
        }
      }
    }
  }
}
```
In logstash.yml to add `dead_letter_queue.enable: true`

Create deadletter queue:
```yml
input {
    generator {
       lines => [
       '{"geoip":{"location":"home"}}'
       ]
       count => 1
    }
 }
 
 filter {
 json {
    source => "[message]"
    remove_field => ["[message]"]
  }
 }

 output {
       elasticsearch {
         index => "test-000001"
         cloud_id => "xxx"
         cloud_auth => "xxx:yyy"
       }
 }
```

 Read deadletter queue:
```yml
input {
    dead_letter_queue {
      path => "PATH_TO_DEADLETTER_QUEUE"
    }
  }
  output {
    stdout {
      codec => rubydebug { metadata => true }
    }
  }
```

In [doc](https://www.elastic.co/guide/en/logstash/8.6/dead-letter-queues.html#dlq-example) we have:
 `"plugin_id" => "fb80f1925088497215b8d037e622dec5819b503e-4",`
 `"plugin_type" => "elasticsearch",`
What we get is:
`"plugin_id" => "elasticsearch"`
`"plugin_type" => "18cd730fa5af8863400b41da0031670ebb1acdfca83c6348e6006a65126a7c8f",`

**Comment by andsel** [comment]
It's an inversion of parameters:
- the call expects .. pluginName, pluginId https://github.com/elastic/logstash/blob/02b83e3840db85467401ff3e5e64791d41e9c508/logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java#L221
- but the caller passes pluginId, pluginName https://github.com/elastic/logstash/blob/02b83e3840db85467401ff3e5e64791d41e9c508/logstash-core/src/main/java/org/logstash/common/AbstractDeadLetterQueueWriterExt.java#L201

**Comment by andsel** [comment]
The issue happens in Logstash core https://github.com/elastic/logstash/pull/14900
